sudo: false
language: node_js
node_js:
  - "6"

before_install:
  - npm install yarn -g

install:
  - yarn

script:
  - npm run lint

# Only build for master & pull-requests
branches:
  only:
    - master
